"""Add membership payment and renewal dates

Revision ID: 31d306e1285f
Revises: 001_initial_baseline
Create Date: 2025-11-22 07:46:14.633382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d306e1285f'
down_revision = '001_initial_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellness_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('completion_criteria', sa.Text(), nullable=True),
    sa.Column('activation_key', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypto_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_cues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('content_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['wellness_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_mentee',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=False),
    sa.Column('mentee_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellness_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('activation_attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['wellness_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('membership_renewal_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('membership_renewal_date')
        batch_op.drop_column('membership_payment_date')

    op.drop_table('wellness_progress')
    op.drop_table('mentor_mentee')
    op.drop_table('mentor_cues')
    op.drop_table('crypto_transactions')
    op.drop_table('wellness_modules')
    # ### end Alembic commands ###
